script:
  - id: update_wifi_led
    mode: restart
    then:
      - lambda: |-
          id(air_purifier).send_wifi_status(
            id(api_connected).state,
            wifi::global_wifi_component->is_connected()
          );
          
esphome:
  name: air-purifier
  friendly_name: "Air Purifier"
  on_boot:
    priority: -100
    then:
      - script.execute: update_wifi_led
      - fan.turn_on: air_purifier_fan

external_components:
  - source: components/
    components: [air_purifier_vital200s]

esp32:
  variant: esp32c3
  framework:
    type: esp-idf

logger:
  level: DEBUG

api:
  encryption:
    key: !secret api_key_air_purifier

ota:
  - platform: esphome

captive_portal:

web_server:
  port: 80

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  on_connect:
    - script.execute: update_wifi_led
  on_disconnect:
    - script.execute: update_wifi_led

binary_sensor:
  - platform: status
    id: api_connected
    on_press:
      - script.execute: update_wifi_led
    on_release:
      - script.execute: update_wifi_led

uart:
  id: uart_bus
  tx_pin: GPIO19
  rx_pin: GPIO18
  baud_rate: 115200

air_purifier_vital200s:
  id: air_purifier
  uart_id: uart_bus
  fan:
    id: air_purifier_fan
    name: "Air Purifier"
  pm25:
    name: "PM2.5"
  air_quality:
    name: "Air Quality"
  display:
    name: "Display"
  display_lock:
    name: "Display Lock"
  light_detection:
    name: "Light Detection"